---
- name: Configure master interface
  lineinfile: >
    dest={{ bond_script_dir }}/ifcfg-{{ bond_master.device }}
    regexp="^\\s*{{ item.key | upper }}="
    line="{{ item.key | upper }}={{ item.value }}"
  with_dict: "{{ bond_master }}"
