---
- name: Configure master interface
  lineinfile: >
    create=yes
    dest={{ bond_script_dir }}/ifcfg-{{ bond_master.device }}
    regexp="^\\s*{{ item.key | upper }}="
    line="{{ item.key | upper }}={{ item.value }}"
  with_dict: "{{ bond_master }}"
  notify: Reboot the server

- name: Configure slave interfaces
  lineinfile: >
    create=yes
    dest={{ bond_script_dir }}/ifcfg-{{ item[0] }}
    regexp="^\\s*{{ item[1] | upper }}="
    line="{{ item[1] | upper }}={{ bond_slaves[item[1]] }}"
  with_nested:
    - >
      {{ ansible_interfaces
      | reject("equalto", ansible_lo.device)
      | reject("equalto", bond_master.device)
      | list }}
    - "{{ bond_slaves.keys() }}"
  notify: Reboot the server
